/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.adminControlador;
import javax.swing.JOptionPane;


/**
 *
 * @author HP
 */
public class inicioSesionAdministrador extends javax.swing.JInternalFrame {

    /**
     * Creates new form inicioSesionAdministrador
     */
    public inicioSesionAdministrador() {
        initComponents();
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpInicio = new javax.swing.JDesktopPane();
        txtEmail = new javax.swing.JTextField();
        jblInicio = new javax.swing.JLabel();
        pwdContra = new javax.swing.JPasswordField();
        jblEmail = new javax.swing.JLabel();
        btnIngresarAdministrador = new javax.swing.JButton();
        jblContra = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jblInicio.setText("INICIO DE SESION ");

        jblEmail.setText("E-MAIL:");

        btnIngresarAdministrador.setText("INGRESAR");
        btnIngresarAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarAdministradorActionPerformed(evt);
            }
        });

        jblContra.setText("CONTRASEÑA:");

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jdpInicio.setLayer(txtEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpInicio.setLayer(jblInicio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpInicio.setLayer(pwdContra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpInicio.setLayer(jblEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpInicio.setLayer(btnIngresarAdministrador, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpInicio.setLayer(jblContra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpInicio.setLayer(btnRegresar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpInicioLayout = new javax.swing.GroupLayout(jdpInicio);
        jdpInicio.setLayout(jdpInicioLayout);
        jdpInicioLayout.setHorizontalGroup(
            jdpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpInicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jdpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdpInicioLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jdpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblContra))
                        .addGap(68, 68, 68)
                        .addGroup(jdpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(pwdContra))
                        .addGap(59, 59, 59))
                    .addGroup(jdpInicioLayout.createSequentialGroup()
                        .addComponent(btnRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIngresarAdministrador))))
            .addGroup(jdpInicioLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jblInicio)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jdpInicioLayout.setVerticalGroup(
            jdpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpInicioLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jblInicio)
                .addGap(29, 29, 29)
                .addGroup(jdpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jdpInicioLayout.createSequentialGroup()
                        .addGroup(jdpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(jdpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jblContra)
                        .addComponent(pwdContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(105, 105, 105)
                .addGroup(jdpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresarAdministrador)
                    .addComponent(btnRegresar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpInicio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarAdministradorActionPerformed
        // TODO add your handling code here:
        adminControlador admin = new adminControlador();
        String email = txtEmail.getText();
        char[] passwordArray = pwdContra.getPassword();
        String contraseña = new String(passwordArray);
            if (email.isEmpty() || contraseña.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
        return;
    }
        boolean autenticado = admin.verificarCredenciales(email, contraseña);
        if (autenticado) {
            menuAdmin ma = new menuAdmin();
            jdpInicio.add(ma);  
            ma.setVisible(true);  
           
    } else {
        JOptionPane.showMessageDialog(this, "Correo/Contraseña Incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnIngresarAdministradorActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarAdministrador;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jblContra;
    private javax.swing.JLabel jblEmail;
    private javax.swing.JLabel jblInicio;
    private javax.swing.JDesktopPane jdpInicio;
    private javax.swing.JPasswordField pwdContra;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
