/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.adminControlador;
import Modelo.administradorModelo;
import com.mysql.cj.protocol.Message;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class inicioSesionAdministrador extends javax.swing.JInternalFrame {

    /**
     * Creates new form inicioSesionAdministrador
     */
    public inicioSesionAdministrador() {
        initComponents();
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpInicio = new javax.swing.JDesktopPane();
        txtEmail = new javax.swing.JTextField();
        jblInicio = new javax.swing.JLabel();
        pwdContra = new javax.swing.JPasswordField();
        jblEmail = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jblContra = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jblInicio.setText("INICIO DE SESION ");

        jblEmail.setText("E-MAIL:");

        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        jblContra.setText("CONTRASEÑA:");

        jdpInicio.setLayer(txtEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpInicio.setLayer(jblInicio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpInicio.setLayer(pwdContra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpInicio.setLayer(jblEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpInicio.setLayer(btnIngresar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpInicio.setLayer(jblContra, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpInicioLayout = new javax.swing.GroupLayout(jdpInicio);
        jdpInicio.setLayout(jdpInicioLayout);
        jdpInicioLayout.setHorizontalGroup(
            jdpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpInicioLayout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jblInicio)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpInicioLayout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addGroup(jdpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpInicioLayout.createSequentialGroup()
                        .addComponent(btnIngresar)
                        .addGap(354, 354, 354))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpInicioLayout.createSequentialGroup()
                        .addGroup(jdpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpInicioLayout.createSequentialGroup()
                                .addComponent(jblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpInicioLayout.createSequentialGroup()
                                .addComponent(jblContra)
                                .addGap(78, 78, 78)))
                        .addGroup(jdpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(pwdContra))
                        .addGap(162, 162, 162))))
        );
        jdpInicioLayout.setVerticalGroup(
            jdpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpInicioLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jblInicio)
                .addGap(77, 77, 77)
                .addGroup(jdpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jdpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblContra)
                    .addComponent(pwdContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnIngresar)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpInicio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpInicio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        adminControlador admin = new adminControlador();
        String email = txtEmail.getText();
        char[] passwordArray = pwdContra.getPassword();
        String contraseña = new String(passwordArray);
            if (email.isEmpty() || contraseña.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
        return;
    }
        boolean autenticado = admin.verificarCredenciales(email, contraseña);
        if (autenticado) {
            menuAdmin ma = new menuAdmin();
            jdpInicio.add(ma);  
            ma.setVisible(true);  
           
    } else {
        JOptionPane.showMessageDialog(this, "Correo/Contraseña Incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnIngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jblContra;
    private javax.swing.JLabel jblEmail;
    private javax.swing.JLabel jblInicio;
    private javax.swing.JDesktopPane jdpInicio;
    private javax.swing.JPasswordField pwdContra;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
