/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.adminControlador;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class inicioSesionLector extends javax.swing.JInternalFrame {

    /**
     * Creates new form inicioSesionLector
     */
    public inicioSesionLector() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpinicio = new javax.swing.JDesktopPane();
        btnCrearUsuario = new javax.swing.JButton();
        jblTitulo = new javax.swing.JLabel();
        btnIngresarUsuario = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        btnRegresarISL = new javax.swing.JButton();
        jblContra = new javax.swing.JLabel();
        jblEmail = new javax.swing.JLabel();
        pwdcontra = new javax.swing.JPasswordField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        btnCrearUsuario.setText("NUEVO USUARIO");
        btnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsuarioActionPerformed(evt);
            }
        });

        jblTitulo.setText("INICIO DE SESION ");

        btnIngresarUsuario.setText("INGRESAR");
        btnIngresarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarUsuarioActionPerformed(evt);
            }
        });

        btnRegresarISL.setText("REGRESAR");

        jblContra.setText("CONTRASEÑA:");

        jblEmail.setText("E-MAIL:");

        jdpinicio.setLayer(btnCrearUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpinicio.setLayer(jblTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpinicio.setLayer(btnIngresarUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpinicio.setLayer(txtEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpinicio.setLayer(btnRegresarISL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpinicio.setLayer(jblContra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpinicio.setLayer(jblEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpinicio.setLayer(pwdcontra, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpinicioLayout = new javax.swing.GroupLayout(jdpinicio);
        jdpinicio.setLayout(jdpinicioLayout);
        jdpinicioLayout.setHorizontalGroup(
            jdpinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpinicioLayout.createSequentialGroup()
                .addGroup(jdpinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdpinicioLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jdpinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblContra)
                            .addComponent(jblEmail)
                            .addComponent(btnCrearUsuario))
                        .addGroup(jdpinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdpinicioLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(btnIngresarUsuario)
                                .addGap(63, 63, 63)
                                .addComponent(btnRegresarISL))
                            .addGroup(jdpinicioLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jdpinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(pwdcontra)))))
                    .addGroup(jdpinicioLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jblTitulo)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jdpinicioLayout.setVerticalGroup(
            jdpinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpinicioLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jblTitulo)
                .addGap(63, 63, 63)
                .addGroup(jdpinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jdpinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblContra)
                    .addGroup(jdpinicioLayout.createSequentialGroup()
                        .addComponent(pwdcontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addGroup(jdpinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIngresarUsuario)
                            .addComponent(btnCrearUsuario)
                            .addComponent(btnRegresarISL))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpinicio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpinicio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearUsuarioActionPerformed

    private void btnIngresarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarUsuarioActionPerformed
        // TODO add your handling code here:
        adminControlador admin = new adminControlador();
        String email = txtEmail.getText();
        char[] passwordArray = pwdcontra.getPassword();
        String contraseña = new String(passwordArray);
            if (email.isEmpty() || contraseña.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
        return;
    }
        boolean autenticado = admin.verificarCredenciales(email, contraseña);
        if (autenticado) {
            menuLector ml = new menuLector();
            jdpinicio.add(ml);  
            ml.setVisible(true);  
           
    } else {
        JOptionPane.showMessageDialog(this, "Correo/Contraseña Incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnIngresarUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearUsuario;
    private javax.swing.JButton btnIngresarUsuario;
    private javax.swing.JButton btnRegresarISL;
    private javax.swing.JLabel jblContra;
    private javax.swing.JLabel jblEmail;
    private javax.swing.JLabel jblTitulo;
    private javax.swing.JDesktopPane jdpinicio;
    private javax.swing.JPasswordField pwdcontra;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
