    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author HP
 */
public class menuAdmin extends javax.swing.JInternalFrame {

    /**
     * Creates new form menuAdmin
     */
    public menuAdmin() {
        initComponents();
        
    }
    
        public void mostrarMenuAdmin() {


       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpmenu = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmtagregaar = new javax.swing.JMenuItem();
        jmtelliminar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout jdpmenuLayout = new javax.swing.GroupLayout(jdpmenu);
        jdpmenu.setLayout(jdpmenuLayout);
        jdpmenuLayout.setHorizontalGroup(
            jdpmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 981, Short.MAX_VALUE)
        );
        jdpmenuLayout.setVerticalGroup(
            jdpmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        jMenu1.setText("Administar Lectores");

        jmtagregaar.setText("Agregar ");
        jmtagregaar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmtagregaarActionPerformed(evt);
            }
        });
        jMenu1.add(jmtagregaar);

        jmtelliminar.setText("Eliminar/Modificar");
        jmtelliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmtelliminarActionPerformed(evt);
            }
        });
        jMenu1.add(jmtelliminar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Administrar Parametros");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpmenu))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpmenu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmtelliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmtelliminarActionPerformed
        // TODO add your handling code here:
            eliminarMoodificarLector eliminar = new eliminarMoodificarLector();
            jdpmenu.add(eliminar);
             eliminar.show();
            
    }//GEN-LAST:event_jmtelliminarActionPerformed

    private void jmtagregaarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmtagregaarActionPerformed
        // TODO add your handling code here:
           agregarLector agregar= new agregarLector();
            jdpmenu.add(agregar);
             agregar.show();
            
    }//GEN-LAST:event_jmtagregaarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpmenu;
    private javax.swing.JMenuItem jmtagregaar;
    private javax.swing.JMenuItem jmtelliminar;
    // End of variables declaration//GEN-END:variables
}
