/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author HP
 */
public class menuAdmin extends javax.swing.JInternalFrame {

    /**
     * Creates new form menuAdmin
     */
    public menuAdmin() {
        initComponents();

    }

    public void mostrarMenuAdmin() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jdpmenu = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiagregar = new javax.swing.JMenuItem();
        jmimodicar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout jdpmenuLayout = new javax.swing.GroupLayout(jdpmenu);
        jdpmenu.setLayout(jdpmenuLayout);
        jdpmenuLayout.setHorizontalGroup(
            jdpmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 981, Short.MAX_VALUE)
        );
        jdpmenuLayout.setVerticalGroup(
            jdpmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        jMenu1.setText("Administar Lectores");

        jmiagregar.setText("Agregar ");
        jmiagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiagregarActionPerformed(evt);
            }
        });
        jMenu1.add(jmiagregar);

        jmimodicar.setText("Modificar/Eliminar ");
        jmimodicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmimodicarActionPerformed(evt);
            }
        });
        jMenu1.add(jmimodicar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Administrar Historias");

        jMenuItem2.setText("Ver historias generadas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpmenu))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpmenu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmimodicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmimodicarActionPerformed
        // TODO add your handling code here:
        eliminarMoodificarLector eliminar = new eliminarMoodificarLector();
        jdpmenu.add(eliminar);
        eliminar.show();

    }//GEN-LAST:event_jmimodicarActionPerformed

    private void jmiagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiagregarActionPerformed
        // TODO add your handling code here:
        agregarLector agregar = new agregarLector();
        jdpmenu.add(agregar);
        agregar.show();

    }//GEN-LAST:event_jmiagregarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        gestionarHistorias gestionar = new gestionarHistorias();
        jdpmenu.add(gestionar);
        gestionar.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JDesktopPane jdpmenu;
    private javax.swing.JMenuItem jmiagregar;
    private javax.swing.JMenuItem jmimodicar;
    // End of variables declaration//GEN-END:variables
}
