    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author HP
 */
public class menuAdmin extends javax.swing.JInternalFrame {

    /**
     * Creates new form menuAdmin
     */
    public menuAdmin() {
        initComponents();
        
    }
    
        public void mostrarMenuAdmin() {


       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpmenuAdmin = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        btnGesionarU = new javax.swing.JButton();
        btnGestionarH = new javax.swing.JButton();
        btnGestionarP = new javax.swing.JButton();
        btnSalirMA = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("QUE ACCIÓN DESEA REALIZAR?");

        btnGesionarU.setText("GESTIONAR USUARIOS");

        btnGestionarH.setText("GESTIONAR HISTORIAS");

        btnGestionarP.setText("GESTIONAR PARAMETROS");

        btnSalirMA.setText("SALIR");
        btnSalirMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirMAActionPerformed(evt);
            }
        });

        jdpmenuAdmin.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpmenuAdmin.setLayer(btnGesionarU, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpmenuAdmin.setLayer(btnGestionarH, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpmenuAdmin.setLayer(btnGestionarP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpmenuAdmin.setLayer(btnSalirMA, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpmenuAdminLayout = new javax.swing.GroupLayout(jdpmenuAdmin);
        jdpmenuAdmin.setLayout(jdpmenuAdminLayout);
        jdpmenuAdminLayout.setHorizontalGroup(
            jdpmenuAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpmenuAdminLayout.createSequentialGroup()
                .addGroup(jdpmenuAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGestionarH)
                    .addGroup(jdpmenuAdminLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1)
                        .addGap(90, 90, 90)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jdpmenuAdminLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(btnGestionarP)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpmenuAdminLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jdpmenuAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpmenuAdminLayout.createSequentialGroup()
                        .addComponent(btnGesionarU)
                        .addGap(256, 256, 256))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpmenuAdminLayout.createSequentialGroup()
                        .addComponent(btnSalirMA)
                        .addGap(18, 18, 18))))
        );
        jdpmenuAdminLayout.setVerticalGroup(
            jdpmenuAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpmenuAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(jdpmenuAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGesionarU)
                    .addComponent(btnGestionarH))
                .addGap(56, 56, 56)
                .addComponent(btnGestionarP)
                .addGap(18, 18, 18)
                .addComponent(btnSalirMA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpmenuAdmin)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpmenuAdmin)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirMAActionPerformed
        // TODO add your handling code here:
        inicioSesionAdministrador sa = new inicioSesionAdministrador();
        sa.setVisible(true);
        sa.show();
        
    }//GEN-LAST:event_btnSalirMAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGesionarU;
    private javax.swing.JButton btnGestionarH;
    private javax.swing.JButton btnGestionarP;
    private javax.swing.JButton btnSalirMA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JDesktopPane jdpmenuAdmin;
    // End of variables declaration//GEN-END:variables
}
