/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author HP
 */
public class menuLector extends javax.swing.JInternalFrame {

    /**
     * Creates new form menuLector
     */
    public menuLector() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpmenuLector = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mncrearHistoria = new javax.swing.JMenu();
        jmtcrear = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmtmirar = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jdpmenuLectorLayout = new javax.swing.GroupLayout(jdpmenuLector);
        jdpmenuLector.setLayout(jdpmenuLectorLayout);
        jdpmenuLectorLayout.setHorizontalGroup(
            jdpmenuLectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );
        jdpmenuLectorLayout.setVerticalGroup(
            jdpmenuLectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        mncrearHistoria.setText("Crear Historia");

        jmtcrear.setText("Crear");
        jmtcrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmtcrearActionPerformed(evt);
            }
        });
        mncrearHistoria.add(jmtcrear);

        jMenuBar1.add(mncrearHistoria);

        jMenu2.setText("Mirar Historias");

        jmtmirar.setText("Mirar Historiaas creadas");
        jMenu2.add(jmtmirar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpmenuLector)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpmenuLector)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmtcrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmtcrearActionPerformed
        // TODO add your handling code here:
             parametrosHistoria crear= new parametrosHistoria();
            jdpmenuLector.add(crear);
             crear.show();
            
    }//GEN-LAST:event_jmtcrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpmenuLector;
    private javax.swing.JMenuItem jmtcrear;
    private javax.swing.JMenuItem jmtmirar;
    private javax.swing.JMenu mncrearHistoria;
    // End of variables declaration//GEN-END:variables
}
