/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author HP
 */
public class parametrosCuentos extends javax.swing.JInternalFrame {

    /**
     * Creates new form crearHistoria
     */
    public parametrosCuentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jdpParametros = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPersonaje2 = new javax.swing.JTextField();
        txtPersonaje1 = new javax.swing.JTextField();
        cmbxGenero = new javax.swing.JComboBox<>();
        btnSalirPH = new javax.swing.JButton();
        btnRegresarPH = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmbxEscenario = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("PERSONAJE 1");

        jLabel3.setText("PERSONAJE 2");

        jLabel2.setText("PERSONAJES");

        jLabel4.setText("GENERO");

        txtPersonaje1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPersonaje1ActionPerformed(evt);
            }
        });

        cmbxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TERROR", "DRAMA", "FANTASIA" }));
        cmbxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxGeneroActionPerformed(evt);
            }
        });

        btnSalirPH.setText("SALIR");
        btnSalirPH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirPHActionPerformed(evt);
            }
        });

        btnRegresarPH.setText("REGRESAR");
        btnRegresarPH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarPHActionPerformed(evt);
            }
        });

        btnContinuar.setText("CONTINUAR");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        jLabel5.setText("ESCENARIO");

        cmbxEscenario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PUEBLO ABANDONADO", "BOSQUE", "LABERINTO INFINITO" }));
        cmbxEscenario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxEscenarioActionPerformed(evt);
            }
        });

        jdpParametros.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpParametros.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpParametros.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpParametros.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpParametros.setLayer(txtPersonaje2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpParametros.setLayer(txtPersonaje1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpParametros.setLayer(cmbxGenero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpParametros.setLayer(btnSalirPH, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpParametros.setLayer(btnRegresarPH, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpParametros.setLayer(btnContinuar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpParametros.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpParametros.setLayer(cmbxEscenario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpParametrosLayout = new javax.swing.GroupLayout(jdpParametros);
        jdpParametros.setLayout(jdpParametrosLayout);
        jdpParametrosLayout.setHorizontalGroup(
            jdpParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpParametrosLayout.createSequentialGroup()
                .addGroup(jdpParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdpParametrosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSalirPH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(btnRegresarPH)
                        .addGap(83, 83, 83)
                        .addComponent(btnContinuar))
                    .addGroup(jdpParametrosLayout.createSequentialGroup()
                        .addGroup(jdpParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdpParametrosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jdpParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jdpParametrosLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(107, 107, 107)
                                        .addComponent(txtPersonaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jdpParametrosLayout.createSequentialGroup()
                                        .addGroup(jdpParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(107, 107, 107)
                                        .addGroup(jdpParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPersonaje2, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                            .addComponent(cmbxGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbxEscenario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jdpParametrosLayout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jdpParametrosLayout.setVerticalGroup(
            jdpParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpParametrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addGroup(jdpParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPersonaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdpParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPersonaje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jdpParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jdpParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbxEscenario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jdpParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalirPH)
                    .addComponent(btnRegresarPH)
                    .addComponent(btnContinuar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpParametros)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpParametros, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPersonaje1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPersonaje1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPersonaje1ActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
        String nombrePersonaje1 = txtPersonaje1.getText();
        String nombrePersonaje2 = txtPersonaje2.getText();

        // Get the genre
        String genero = cmbxGenero.getSelectedItem().toString();

        // Get the scenario
        String escenario = cmbxEscenario.getSelectedItem().toString();

        
        opTerrorBosque opTB = new opTerrorBosque(nombrePersonaje1, nombrePersonaje2,genero,escenario);

        // Start the game
        opTB.add(opTB);

        // Close the current window
        this.btnContinuar()
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnRegresarPHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarPHActionPerformed
        // TODO add your handling code here:
        menuLector mL = new menuLector();
        jdpParametros.add(mL);
        mL.show();

    }//GEN-LAST:event_btnRegresarPHActionPerformed

    private void cmbxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxGeneroActionPerformed

        cmbxGenero.addItem("Terror");
        cmbxGenero.addItem("Drama");
        cmbxGenero.addItem("Fantasía");


    }//GEN-LAST:event_cmbxGeneroActionPerformed

    private void btnSalirPHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirPHActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnSalirPHActionPerformed

    private void cmbxEscenarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxEscenarioActionPerformed

        cmbxEscenario.addItem("Pueblo abandonado");
        cmbxEscenario.addItem("Bosque");
        cmbxEscenario.addItem("Laberinto infinito");

    }//GEN-LAST:event_cmbxEscenarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnRegresarPH;
    private javax.swing.JButton btnSalirPH;
    private javax.swing.JComboBox<String> cmbxEscenario;
    private javax.swing.JComboBox<String> cmbxGenero;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JDesktopPane jdpParametros;
    private javax.swing.JTextField txtPersonaje1;
    private javax.swing.JTextField txtPersonaje2;
    // End of variables declaration//GEN-END:variables
}
